/*
 * Hahabit API
 *
 * API for the Hahabit Habit Tracker
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetHabitsForDate200Response {
    #[serde(rename = "habits")]
    pub habits: Vec<crate::models::HabitForDate>,
}

impl GetHabitsForDate200Response {
    pub fn new(habits: Vec<crate::models::HabitForDate>) -> GetHabitsForDate200Response {
        GetHabitsForDate200Response {
            habits,
        }
    }
}


