/*
 * Hahabit API
 *
 * API for the Hahabit Habit Tracker
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct HabitForDate {
    #[serde(rename = "habitId")]
    pub habit_id: i64,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "date")]
    pub date: String,
    #[serde(rename = "trackingId", deserialize_with = "Option::deserialize")]
    pub tracking_id: Option<i64>,
}

impl HabitForDate {
    pub fn new(habit_id: i64, description: String, date: String, tracking_id: Option<i64>) -> HabitForDate {
        HabitForDate {
            habit_id,
            description,
            date,
            tracking_id,
        }
    }
}


