/*
 * Hahabit API
 *
 * API for the Hahabit Habit Tracker
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct HabitCreateRequest {
    #[serde(rename = "description")]
    pub description: String,
}

impl HabitCreateRequest {
    pub fn new(description: String) -> HabitCreateRequest {
        HabitCreateRequest {
            description,
        }
    }
}


