/*
 * Hahabit API
 *
 * API for the Hahabit Habit Tracker
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct HabitForDate {
    #[serde(rename = "habitId", skip_serializing_if = "Option::is_none")]
    pub habit_id: Option<i64>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "date", skip_serializing_if = "Option::is_none")]
    pub date: Option<String>,
    #[serde(rename = "trackingId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tracking_id: Option<Option<i64>>,
}

impl HabitForDate {
    pub fn new() -> HabitForDate {
        HabitForDate {
            habit_id: None,
            description: None,
            date: None,
            tracking_id: None,
        }
    }
}


